### ISSUE TITLE
Building with URP+Input Profiles Loader fails

### ISSUE THREAD

**Issue by msub2** [De-Panther/webxr-input-profiles-loader#5]
I was doing some experiments comparing builds between some baseline WebXR projects in Unity 2019.4.13f1, and I found that while attempting to build a project with the Input Profiles Loader and URP, the build fails from two files being used in gltfast

`Library\PackageCache\com.atteneder.gltfast@2.5.0\Runtime\Scripts\MaterialGenerator.cs(48,42): error CS0161: 'MaterialGenerator.GetDefaultMaterialGenerator()': not all code paths return a value`

and

`Library\PackageCache\com.atteneder.gltfast@2.5.0\Runtime\Scripts\StandardShaderHelper.cs(136,37): error CS0103: The name 'KW_ALPHABLEND_ON' does not exist in the current context`

Don't have time to test further at the moment, but thought I'd bring it to your attention. Possibly needs to be addressed upstream? Would need to look closer at the code.

**Comment by De-Panther** [comment]
Thanks for sharing.
Could you please report those errors at https://github.com/atteneder/glTFast/issues ?

It seems that since glTFast 2.5.0 there were changes to `StandardShaderHelper.cs`, so the error of `The name 'KW_ALPHABLEND_ON' does not exist in the current context` might be fixed.

There were no changes since 2.5.0 to `MaterialGenerator.cs`, so there's still error in `MaterialGenerator.GetDefaultMaterialGenerator()`.

Once there'll be a new glTFast version I'll upgrade the required version in this package.

**Comment by msub2** [comment]
FYI looks like this was fixed upstream  atteneder/glTFast#121

**Comment by De-Panther** [comment]
Version 0.3.2
Updated glTFast package to 3.0.1.
